version: 2.1

orbs:
  win: circleci/windows@2.2.0
  golang: cci-orb/golang@0.1.17

jobs:
  unit_test_windows:
    executor:
      name: win/default
#      name: golang/windows
    environment:
      LOGPARSERVERSION: "v0.30.23"
      TERRAFORMVERSION: "0.13.5"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-cache-{{ .Branch }}-{{ checksum "go.sum" }}
      - run: go version
      - run: go env
      - run: |
          # https://discuss.circleci.com/t/access-denied-error-while-trying-to-download-software-on-windows-cirlcleci-environment/32809/3
          $ProgressPreference = "SilentlyContinue"
          Invoke-RestMethod -Method Get -Uri "https://releases.hashicorp.com/terraform/$($env:TERRAFORMVERSION)/terraform_$($env:TERRAFORMVERSION)_windows_amd64.zip" -OutFile "c:/terraform_windows_amd64.zip"
          $ProgressPreference = "Continue"
      - run: Expand-Archive -Path "c:/terraform_windows_amd64.zip" -Destination "C:/Tools/terraform"
      - run: mkdir "C:/Tools/logparser"
      - run: |
          # https://discuss.circleci.com/t/access-denied-error-while-trying-to-download-software-on-windows-cirlcleci-environment/32809/3
          $ProgressPreference = "SilentlyContinue"
          Invoke-WebRequest -Method Get -Uri "https://github.com/gruntwork-io/terratest/releases/download/$($env:LOGPARSERVERSION)/terratest_log_parser_windows_amd64.exe" -OutFile "C:/Tools/logparser/terratest_log_parser.exe"
          $ProgressPreference = "Continue"
      - run: $env:PATH="$env:PATH;C:\Tools\terraform\;C:\Tools\logparser\"
      - run: |
          go version
          C:\Tools\terraform\terraform.exe version
      - run: |
          go get
      - run: |
          $env:PATH="$env:PATH;C:\Tools\terraform\;C:\Tools\logparser\"
          go get
      - run: |
          $env:PATH="$env:PATH;C:\Tools\terraform\;C:\Tools\logparser\"
          go test ./cli
      - save_cache:
          when: always
          key: v4-cache-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - $GOPATH/pkg/mod
workflows:
  version: 2
  build-and-test:
    jobs:
      - unit_test_windows
